# Generated by Django 3.2 on 2022-09-02 05:48

from django.db import migrations


def forwards_func(apps, schema_editor):
    # Get model
    Courses = apps.get_model("mainapp", "Courses")
    # Create model's objects
    Courses.objects.create(
        name="Название курса 1",
        description="Описание курса 1",
        # description_as_markdown=True,
        cost="3500",
        cover="img/no_image.svg",
        created="2021-07-11T08:24:53.084Z",
        updated="2021-07-11T09:06:35.322Z"
    )
    Courses.objects.create(
        name="Название курса 2",
        description="Описание курса 2",
        description_as_markdown=True,
        cost="5200",
        cover="img/no_image.svg",
        created="2021-07-11T08:24:53.084Z",
        updated="2021-07-11T09:06:35.322Z"
    )


def reverse_func(apps, schema_editor):
    # Get model
    Courses = apps.get_model("mainapp", "Courses")
    # Delete objects
    Courses.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_data_migrations'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
