# Generated by Django 3.2 on 2022-09-02 05:49

from django.db import migrations
from mainapp.models import Courses

def forwards_func(apps, schema_editor):
    # Get model
    Lesson = apps.get_model("mainapp", "Lesson")
    # Create model's objects
    Lesson.objects.create(
        course=Courses.objects.get(pk=3),
        num=9,
        title="Дополнительный урок",
        description="Описание урока",
        description_as_markdown=True,
        created="2021-07-11T12:53:26.832Z",
        updated="2021-07-11T12:53:26.833Z"
    )
    Lesson.objects.create(
        course=Courses.objects.get(pk=3),
        num=10,
        title="Еще один дополнительный урок",
        description="Описание урока",
        description_as_markdown=False,
        created="2021-07-11T12:53:26.832Z",
        updated="2021-07-11T12:53:26.833Z"
    )


def reverse_func(apps, schema_editor):
    # Get model
    Lesson = apps.get_model("mainapp", "Lesson")
    # Delete objects
    Lesson.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_courses_migration'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
