# Generated by Django 3.2 on 2022-09-02 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_lessons_migration'),
    ]

    operations = [
    ]
