# Generated by Django 4.1.1 on 2022-09-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0006_auto_20220914_1634"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
